version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: kioskos_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-kioskos_db}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - kioskos_net
      # Se asume que web_proxy es la red de traefik
      - web_proxy
    restart: always

  adminer:
    image: adminer
    container_name: kioskos_adminer
    environment:
      - ADMINER_DEFAULT_SERVER=kioskos_mysql
    restart: always
    networks:
      - kioskos_net
    labels:
      - "traefik.enable=true"
      # Cambia este host por el dominio final para el db-manager
      - "traefik.http.routers.kioskos-adminer.rule=Host(`db.tudominio.com`)"
      - "traefik.http.routers.kioskos-adminer.priority=100"
      - "traefik.http.services.kioskos-adminer.loadbalancer.server.port=8080"
  
  backend:
    build: 
      context: ./backend
      # Usar Dockerfile normal ya que NestJS compila rápido o puedes hacer path a .prod
    container_name: kioskos_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE:-kioskos_db}
      DB_SYNCHRONIZE: "false" # Migraciones mandan
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
    labels:
      - "traefik.enable=true"
      # El path predominante es tu dominio (reemplazar "pos.tudominio.com")
      - "traefik.http.routers.kioskos-backend.rule=Host(`pos.tudominio.com`) && PathPrefix(`/api`)"
      - "traefik.http.routers.kioskos-backend.entrypoints=web"
      - "traefik.http.routers.kioskos-backend.priority=100"
      - "traefik.http.services.kioskos-backend.loadbalancer.server.port=3000"
    networks:
      - kioskos_net
    depends_on:
      - mysql
    restart: always

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: kioskos_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kioskos-frontend.rule=Host(`pos.tudominio.com`)"
      - "traefik.http.routers.kioskos-frontend.entrypoints=web"
      - "traefik.http.routers.kioskos-frontend.priority=1"
      - "traefik.http.services.kioskos-frontend.loadbalancer.server.port=80"
    networks:
      - kioskos_net
    depends_on:
      - backend
    restart: always

  db-backup:
    image: fradelg/mysql-cron-backup
    container_name: kioskos_db_backup
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=${DB_PASSWORD}
      - MAX_BACKUPS=7
      - CRON_TIME=0 4 * * * # 4:00 AM diario
    volumes:
      - ./mysql/backups:/backup
    networks:
      - kioskos_net
    depends_on:
      - mysql
    restart: always

networks:
  kioskos_net:
    driver: bridge
  web_proxy:
    external: true
