version: "3.9"

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "8080:80"
    environment:
      - DOCKER_API_VERSION=1.53
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/dynamic.yml:/dynamic/dynamic.yml
    networks:
      - tms_net
    restart: always

  mysql:
    image: mysql:8.0
    container_name: tms_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: nest_db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - tms_net
      - web_proxy
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: tms_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpass
      PMA_ABSOLUTE_URI: http://pma.agronomic-tms.dariassoft.com.ar/
    networks:
      - tms_net
    depends_on:
      - mysql
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`pma.agronomic-tms.dariassoft.com.ar`)"
      - "traefik.http.routers.phpmyadmin.priority=100"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.phpmyadmin-ipwhitelist.ipwhitelist.sourcerange=0.0.0.0/0"
      - "traefik.http.routers.phpmyadmin.middlewares=phpmyadmin-ipwhitelist"
    restart: always

  adminer:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=tms_mysql
    restart: always
    networks:
      - tms_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`adminer.agronomic-tms.dariassoft.com.ar`)"
      - "traefik.http.routers.adminer.priority=100"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.adminer-ipwhitelist.ipwhitelist.sourcerange=0.0.0.0/0"
      - "traefik.http.routers.adminer.middlewares=adminer-ipwhitelist"
      
  backend:
    build: ./backend
    container_name: tms_backend
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: nest_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`agronomic-tms.dariassoft.com.ar`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.priority=100"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    networks:
      - tms_net
    depends_on:
      - mysql
    restart: always

  frontend:
    build: ./frontend
    container_name: tms_frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`agronomic-tms.dariassoft.com.ar`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - tms_net
    depends_on:
      - backend
    restart: always
  db-backup:
    image: fradelg/mysql-cron-backup
    container_name: tms_db_backup
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASS=rootpass
      - MAX_BACKUPS=7 # Conserva solo los últimos 7 días para no llenar el disco
      - CRON_TIME=0 3 * * * # Se ejecuta todos los días a las 3:00 AM
    volumes:
      - ./mysql/backups:/backup # Los backups aparecerán en esta carpeta de tu VPS
    networks:
      - tms_net
    depends_on:
      - mysql
    restart: always

networks:
  tms_net:
    driver: bridge
  web_proxy:
    external: true
